### PR TITLE
Complete overhaul of apt and related scripts

### LINKED ISSUE #77: apt argument order
One of the error messages from binary apt:

E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

That command works fine with binary apt, but it won't work on Mint because the apt script currently cannot handle the reversed argument order, it is hardcoded to look for the command only in the first argument:

https://github.com/linuxmint/mintsystem/blob/master/usr/local/bin/apt#L80

Suggest to instead check all arguments for a known command, use the rest as options.

### LINKED ISSUE #78: apt not supporting showsrc command
binary apt has a showsrc command, the wrapper does not. Needs to be added to the command list for apt in 
https://github.com/linuxmint/mintsystem/blob/master/usr/local/bin/apt#L86

Description as per apt-cache:
showsrc - Show source records

### LINKED ISSUE #79: mint-apt-download.py
This part doesn't work and hasn't in a while:

`            os.system("LC_ALL=C apt-get install --dry-run %s | grep ^Inst | awk {'print $2;'} | xargs aptitude download -r" % package.name)
`

`aptitude download` is a wrapper for apt, thus this calls `apt -r download`, which fails due to the bug in the apt script I reported [here](https://github.com/linuxmint/mintsystem/issues/77).
It would however fail regardless because the -r is no valid option for apt or apt-get.

Suggest to simply replace `aptitude download -r` with `/usr/bin/apt download`

### LINKED ISSUE #86: mint-apt-recommends.py bug and suggestion
apt recommends produces nonsensical output. 

### Example
(with debug output enabled, missing packages are marked [MISSING]):
```
$ apt recommends mpv
  mpv 
   youtube-dl [MISSING]
    python3-pkg-resources 
   libarchive13 
    libacl1 
     libattr1 
      libc6 
       libgcc1 
        gcc-8-base 
    libbz2-1.0 
    liblz4-1 
    liblzma5 
    liblzo2-2 
     multiarch-support 
    libnettle6 
    libxml2 
     libicu60 
      libstdc++6 
     zlib1g 
   libasound2 
    libasound2-data 
   libass9 
    libfontconfig1 
     libexpat1 
     libfreetype6 
      libpng16-16 
     fontconfig-config 
      ucf 
       debconf 
        perl-base 
         dpkg 
          libselinux1 
           libpcre3 
          libzstd1 
          tar 
       coreutils 
       sensible-utils 
      fonts-dejavu-core 
      fonts-liberation 
    libfribidi0 
    libharfbuzz0b 
     libglib2.0-0 
      libffi6 
      libmount1 
       libblkid1 
        libuuid1 
     libgraphite2-3 
   libavcodec58 
    libswresample3 
     libavutil56 
      libdrm2 
       libdrm-common 
      libva-drm2 
       libva2 
      libva-x11-2 
       libx11-6 
        libxcb1 
         libxau6 
         libxdmcp6 
          libbsd0 
        libx11-data 
       libxext6 
       libxfixes3 
      libvdpau1 
     libsoxr0 
      libgomp1 
    libcairo2 
     libpixman-1-0 
     libxcb-render0 
     libxcb-shm0 
     libxrender1 
    libcodec2-0.8.1 
    libcrystalhd3 
    libgsm1 
    libmp3lame0 
    libopenjp2-7 
    libopus0 
    librsvg2-2 
     libcroco3 
     libgdk-pixbuf2.0-0 
      libjpeg8 
       libjpeg-turbo8 
      libtiff5 
       libjbig0 
      shared-mime-info 
      libgdk-pixbuf2.0-common 
     libpango-1.0-0 
      fontconfig 
      libthai0 
       libthai-data 
       libdatrie1 
     libpangocairo-1.0-0 
      libpangoft2-1.0-0 
    libshine3 
    libsnappy1v5 
    libspeex1 
    libtheora0 
     libogg0 
    libtwolame0 
    libvorbis0a 
    libvorbisenc2 
    libvpx5 
    libwavpack1 
    libwebp6 
    libwebpmux3 
    libx264-152 
    libx265-160 
     libnuma1 
    libxvidcore4 
    libzvbi0 
     libzvbi-common 
   libavdevice58 
    libavfilter7 
     libavformat58 
      libbluray2 
       libaacs0 [MISSING]
        libgcrypt20 
         libgpg-error0 
      libchromaprint1 
       libavcodec-extra57 
        libavutil55 
        libopencore-amrnb0 
        libopencore-amrwb0 
        libswresample2 
        libvo-amrwbenc0 
        libx265-146 
      libgme0 
      libgnutls30 
       libgmp10 
       libhogweed4 
       libidn2-0 
        libunistring2 
       libp11-kit0 
       libtasn1-6 
      libopenmpt0 
       libmpg123-0 
       libvorbisfile3 
      libssh-gcrypt-4 
       libgssapi-krb5-2 
        libk5crypto3 
         libkrb5support0 
        libkrb5-3 
         libkeyutils1 
     libpostproc55 
     libswscale5 
     libbs2b0 
     libflite1 
     liblilv-0-0 
      libserd-0-0 
      libsord-0-0 
      libsratom-0-0 
     libmysofa0 
     libopencv-core3.2 
      libtbb2 
     libopencv-imgproc3.2 
     librubberband2 
      libfftw3-double3 
      libsamplerate0 
     libzmq5 
      libnorm1 
      libpgm-5.2-0 
      libsodium23 
    libavc1394-0 
     libraw1394-11 
    libcaca0 
     libncursesw5 
      libtinfo5 
     libslang2 
    libcdio-cdda2 
     libcdio17 
    libcdio-paranoia2 
    libdc1394-22 
     libusb-1.0-0 
      libudev1 
    libgl1 
     libglvnd0 
     libglx0 
      libglx-mesa0 
       libglapi-mesa 
       libx11-xcb1 
       libxcb-dri2-0 
       libxcb-dri3-0 
       libxcb-glx0 
       libxcb-present0 
       libxcb-sync1 
       libxdamage1 
       libxshmfence1 
       libxxf86vm1 
       libgl1-mesa-dri 
        libdrm-amdgpu1 
        libdrm-intel1 
         libpciaccess0 
        libdrm-nouveau2 
        libdrm-radeon1 
        libelf1 
        libllvm6.0 
         libedit2 
        libsensors4 
    libiec61883-0 
    libjack-jackd2-0 
    libopenal1 
     libopenal-data 
     libsndio6.1 
    libpulse0 
     libasyncns0 
     libdbus-1-3 
      libsystemd0 
     libsndfile1 
      libflac8 
     libwrap0 
    libsdl2-2.0-0 
     libwayland-client0 
     libwayland-cursor0 
     libwayland-egl1 
     libxcursor1 
     libxi6 
     libxinerama1 
     libxkbcommon0 
      xkb-data 
     libxrandr2 
     libxss1 
      x11-common 
       lsb-base 
    libsndio7.0 
    libxcb-shape0 
    libxcb-xfixes0 
    libxv1 
   libcdio18 
   libdvdnav4 
    libdvdread4 
   libegl1 
    libegl-mesa0 
     libgbm1 
      libwayland-server0 
   liblcms2-2 
   liblua5.2-0 
   libsmbclient 
    samba-libs 
     libavahi-client3 
      libavahi-common3 
       libavahi-common-data 
     libcap2 
     libcups2 
     libjansson4 
     libldap-2.4-2 
      libgssapi3-heimdal 
       libasn1-8-heimdal 
        libroken18-heimdal 
       libhcrypto4-heimdal 
        libheimbase1-heimdal 
       libheimntlm0-heimdal 
        libkrb5-26-heimdal 
         libhx509-5-heimdal 
          libwind0-heimdal 
         libsqlite3-0 
      libsasl2-2 
       libsasl2-modules-db 
        libdb5.3 
      libldap-common 
     libldb1 
      libtalloc2 
      libtdb1 
      libtevent0 
     libpam0g 
      libaudit1 
       libaudit-common 
       libcap-ng0 
     libpopt0 
     libpython2.7 
      libpython2.7-stdlib 
       libpython2.7-minimal 
       mime-support 
       libreadline7 
        readline-common 
         install-info 
       libssl1.1 
     libwbclient0 
     python-talloc 
   libuchardet0 
   libva-wayland2 
   libvulkan1 

The following missing recommended packages were found for mpv:

    libaacs0
    youtube-dl

You can install them by typing the following command:

    apt install libaacs0 youtube-dl
```
### Problem:
Of those two, only `youtube-dl` is a missing direct recommend:
```
$ apt show mpv
[...]
Recommends: xdg-utils, youtube-dl (>= 2014.11.26
```
Direct recommends are the only thing I would want to see as the output of that command.

`libaacs0` is a recommendation of the `libbluray2` package far down the list. Other recommended packages in the tree are not listed, in particular recommended packages of recommended packages. There is no logic to this limitation. If you go recursive then go fully recursive.

### Proposed solution:
Make default operation non-recursive: 

```
$ apt recommends mpv

The following missing recommended packages were found for mpv:

    youtube-dl

You can install them by typing the following command:

    apt install youtube-dl
```
but add a --recursive parameter for a fully recursive output:
```
$ apt recommends mpv --recursive

The following missing recommended packages were found for mpv:

    aria2
    libaacs0
    libbdplus0
    mplayer
    phantomjs
    python3-pyxattr
    rtmpdump
    va-driver-all
    vdpau-driver-all
    youtube-dl

You can install them by typing the following command:

    apt install aria2 libaacs0 libbdplus0 mplayer phantomjs python3-pyxattr rtmpdump va-driver-all vdpau-driver-all youtube-dl
```

### PR DESCRIPTION
**Pull request by gm10**
**Modified and Fixed Commands:**
- `add-repository` works again
- `changelog` command can now retrieve full changelogs for almost any
  package and retrieves changelogs for installed packages locally
  (unless `--no-local` was specified) - if download size exceeds 2.5 MB
  the user is asked for confirmation
- `download` rewritten (fixes #79)
  - now supports version and release declaration,
  - now supports multiple packages in the argument,
  - only creates a .tar.gz if at least 2 packages were downloaded,
  - no longer risks overwriting files in the home folder,
  - only refreshes the cache if older than 24h, and
  - has improved error checking, handling and messaging, including
    handling of broken dependencies
- `edit-sources` is now using nano directly instead of binary apt since
  the latter cannot open symlinked source files
- `recommends` rewritten, now defaults to non-recursive mode and has a
  `-R` / `--recursive` parameter for recursive mode (fixes #86)
- `search` gained an optional `--apt` parameter to use apt instead of
  aptitude for the search
- `version` is now running dpkg-query directly instead of going through
  an external script
- `help` output reformatted for easier readability
- binary `apt` is used for most commands, where available

**New Commands:**
- `auto-clean` & `auto-remove` aliases added for binary apt compatibility
- `add-key`: download and add key id from keyserver or from file
- `listi`: short for list --installed
- `listu`: short for list --upgradable
- `purgeall`: short for purge --autoremove
- `purge-residual`: purge residual configuration
- `showsrc`: show source records (fixes #78)
- `--version`: binary apt version passthrough
- `unmarkauto`: alias for markmanual

**Removed Commands:**
- `stats`
- `sources` (just the alias, too easy to confuse with the source command)

**Other Fixes and Changes:**
- options beginning with a dash can now be entered before the command (fixes #77)
- proper handling of quotes and escaped characters in parameters
- bash completion rewritten, now supports all commands and most options
- `apt` no longer asks for `sudo` privileges if a valid simulation argument
  was used
- highlighting limited to `aptitude` search, now supports multiple search
  terms and handles parameters
- Sorting and highlighting is now done internally
- removed the no longer needed `highlight-mint` script
- signals like Ctrl+C are handled, with signals that pause execution
  leading to termination to prevent lingering dpkg lock
- usage text corrected and amended
- added ./test script to the source as with other Mint packages
- added `python3-apt` dependency
- likely more

**Depends on:**
https://github.com/linuxmint/mint-common/pull/31

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi @gm10 

Sorry for the delay, it's a pity you mixed different things in the same PR.

I'll pick your fix for apt download and send an update to 19.

The rest will be considered for 19.1.

PS: We want to stay with aptitude for "search". The search feature in /usr/bin/apt isn't as useful (you can't grep it easily, there's no state search... for instance "apt search ~c" etc..).

**Comment by gm10** [comment]
What a beautiful rebase, lol. I was missing some commit from master but merge wouldn't pick up on it for some reason. Lovely. This PR is beyond cherry-picking, anyway. :D

**Comment by muzena** [comment]
@gm10 
> I'm using it to add better changelog support for mintupdate as well

Can you fix/or do something, previously it work mintupdate changelog only for launchapad.net PPA repos, now sometimes work sometimes don't work.
For repos outside launchpad mintupdate changelog don't work.

**Comment by gm10** [comment]
@muzena mintupdate should still work correctly for PPAs (only shows the latest change though if I recall correctly), but you'd best discuss that in a mintupdate issue report. Integrating my own changelog module here into mintupdate won't happen before LM19.2, if at all. Again, wrong place to discuss this.

**Comment by muzena** [comment]
@gm10 
Today I noticed that after these changes can't open from synaptic repositories.
Synaptic > Settings > Repositories

**Comment by gm10** [comment]
@muzena hello again, but I suspect you are still in the very wrong place. What changes are you talking about? Can't be the ones in this pull request right here, are they? ;)

**Comment by muzena** [comment]
@gm10 
Since [Gwendal LE BIHAN nightly PPA](https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/cinnamon-nightly) do not work anymore, I made my own [Cinnamon GIT PPA](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/cinnamon-nightly).
This PPA is syncing every 5h and if changes in git made it automatically generates deb packages.

I don't know some changes in mintsources, mint-common, mintsystem or some other package.

**Comment by muzena** [comment]
This is error from terminal when I click on:
Synaptic > Settings > Repositories

Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1735, in <module>
    Application().run()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 801, in __init__
    self.apt = mintcommon.APT(self._main_window)
AttributeError: module 'mintcommon' has no attribute 'APT'

**Comment by gm10** [comment]
@muzena we're not guaranteeing that non-release versions to work. We're currently making changes to a large number of repositories. Your problem is you do not have the latest version of all of them. But even so we're not guaranteeing it will always work. Running "nightlies" is a bad idea. 

Either way, this is really entirely unrelated to both mintsystem and this PR, so I respectfully ask to create your own issue next time in the appropriate repository (but not for something like this, it's a self-inflicted problem).

**Pull request closed without merging**
